version: "3.8"
services:
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        env_file:
            - .env
    backend:
        image: yagnikpt/pvp-rps-server:1.0.0
        ports:
            - "3000:3000"
        depends_on:
            - redis
volumes:
    redis-data:
